# run spring-boot with this profile activated with the following command:
# ./mvnw spring-boot:run "-Dspring-boot.run.profiles=h2"

# H2 embedded database configuration to run without mysql
spring.datasource.url=jdbc:h2:./test
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'create' drops and recreates the schema on startup
# `update` to only update the schema during startup
# 'create-drop' to create on startup and drop on shutdown
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

# Debugging (optional)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
